### ISSUE TITLE
Add state names as resources to strings.xml 

### ISSUE THREAD

**Issue by goforbg** [goforbg/ClickableMapView#2]
Currently, all the states are just hardcoded, we need to extract them as resources to strings.xml

**Comment by acasadoquijada** [comment]
I can work on this, can you assign me the issue?

**Comment by acasadoquijada** [comment]
I just downloaded the code and checked there is not harcoded strings in the code.

**Comment by goforbg** [comment]
@acasadoquijada please check ic_india_map vs ic_nepal_map, 
the strings in nepal's maps are not hardcorded, while in India it is.

**Comment by acasadoquijada** [comment]
@goforbg thanks for the clarification!

**Comment by goforbg** [comment]
@acasadoquijada Good job.
